app = "sinais-b3-bot"

[build]
  builder = "paketobuildpacks/builder:base"

[processes]
  app = "python bot.py"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 8080
    handlers = []
