app = "sinais-b3-bot"

[build]

[env]
  TELEGRAM_TOKEN = "seu_token_aqui"
  TELEGRAM_CHAT_ID = "seu_chat_id_aqui"
  ALPHA_VANTAGE_KEY = "sua_key_principal_aqui"

[processes]
  app = "python bot.py"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 8080
    handlers = []
